### ISSUE TITLE
Authoritative source comments are not displayed

### ISSUE THREAD

**Issue by skalee** [geolexica/osgeo.geolexica.org#39]
Some concepts have untypical source entries, for example:

```
term: catalogue service
termid: 35
eng:
  id: 35
  definition: allows the publication and searching of information (metadata) describing
    data (cartography), services, applications and any other kind of resources. The
    catalogue services are necessary to supply search and invocation capabilities
    over registered resources within an SDI. A Open Geospatial Consortium spec establishes
    how a Catalogue Service must be standard and interoperable.
  language_code: eng
  notes: []
  examples: []
  authoritative_source:
    comment: GVSIG_1-0_2011
  terms:
  - type: expression
    designation: catalogue service
    normative_status: preferred
```

or:

```
term: ISO SQL/MM
termid: 203
eng:
  id: 203
  definition: database language intended for for spatial applications based on SQL
    defined by ISO/IEC 13249-3:2016
  language_code: eng
  notes: []
  examples: []
  authoritative_source:
    comment: Sandro
  terms:
  - type: expression
    designation: ISO SQL/MM
    normative_status: preferred
```

Note that they feature `comment` instead of more typical `link` or `ref`/`clause` pair. Whilst such concepts are correct, the resulting page is not:

![Zrzut ekranu 2021-01-16 o 10 17 56](https://user-images.githubusercontent.com/154287/104943379-f63bd100-59b5-11eb-89c6-e528a9fcb311.png)

----

Also, some concepts may feature mix of `ref`, `clause`, and `comment`, for example:

```
term: metadata
termid: 233
eng:
  id: 233
  definition: information about a resource
  language_code: eng
  notes: []
  examples: []
  authoritative_source:
    ref: ISO 19115-1:2014
    clause: '4.10'
    comment: modified — An admitted term from OSGeo has been added.
  terms:
  - type: expression
    designation: metadata
    normative_status: preferred
  - type: expression
    designation: geospatial metadata
    normative_status: preferred
```

This is also correct, but only ref and clause are presented on page, whereas important comment is missing:

> ![Zrzut ekranu 2021-01-16 o 10 28 44](https://user-images.githubusercontent.com/154287/104943616-4fa40000-59b6-11eb-91dd-4bba43caa245.png)

----

@ronaldtse Clarification needed how it is expected to look like.

This issue has been extracted from https://github.com/geolexica/osgeo-termbase/pull/8.

**Comment by ronaldtse** [comment]
The authorative_source structure was meant to be:
```yaml
  authoritative_source:
    ref: ISO 19115-1:2014    <=== actual source document
    clause: '4.10'             <=== internal link within the document 
    comment: modified — An admitted term from OSGeo has been added.  <=== the difference between source document term and this term
```

I think we should transition to use the new concept structure we have at iev-data, where the authoritative_source is a relationship.
