### ISSUE TITLE
Authoritative sources should be relationships (like in IEV)

### ISSUE THREAD

**Issue by skalee** [geolexica/osgeo.geolexica.org#42]
> I think we should transition to use the new concept structure we have at iev-data, where the authoritative_source is a relationship.

_Originally posted by @ronaldtse in https://github.com/geolexica/osgeo.geolexica.org/issues/39#issuecomment-762721644_

**Comment by HassanAkbar** [comment]
@ronaldtse There is no field for `comment` in the [ConceptSource](https://github.com/glossarist/concept-model/blob/main/models/concepts/ConceptSource.lutaml) model. How do you suggest we should handle this?

**Comment by ronaldtse** [comment]
Where do we have "comment"? If we need it we can add it.

**Comment by HassanAkbar** [comment]
We currently do not have any `comment` field. We can add a comment field in the `ConceptSource ` but there are 2 types of comments

1. That starts with `modified -  `, e.g

   ```yaml
      authoritative_source:
        ref: ISO 19115-1:2014
        clause: '4.10'
        comment: modified — An admitted term from OSGeo has been added.
     ``` 
2. That does not starts with `modified -  `, e.g

   ```yaml
      authoritative_source:
          comment: Combo of a couple of sources
     ``` 

@ronaldtse I have 2 questions:
1. Where should we add the comment field? 
2. We have a `modification` field in the [`ConceptSource`](https://github.com/glossarist/concept-model/blob/main/models/concepts/ConceptSource.lutaml#L20) model. Should we convert the comment of concepts like `1` and save them in the `modification` field or should we just treat them as comments for now?
